require("user.options")
require("user.globals")
require("user.lazy")
require("user.autocommands")
require("user.cmp")
require("user.treesitter")
require("user.autopairs")
-- require("user.gitsigns")
require("user.nvim-tree")
require("user.bufferline")
require("user.lualine")
require("user.toggleterm")
require("user.project")
require("user.illuminate")
require("user.lsp")
-- require("user.dap")
